### ISSUE TITLE
subfolders

### ISSUE THREAD

**Issue by blachawk** [mikechernev/dockerised-php#9]
Not sure if this is issue related, but there appears to be a lack of understanding on how to allow sub folders to exist.  What would be the recommendation from our site.conf file to allow any sub folder to exist and be accessible in the browser after we do our normal docker-compose up -d?

This is my sample code I'm working on based on a tutorial:

```
server {
    index index.php index.html;
    server_name php-docker.local;
    error_log  root /var/log/nginx/error.log;
    access_log root /var/log/nginx/access.log;
    root /phpweb;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

```
Thanks for any direction

**Comment by Feft** [comment]
The root folder in tutorial is **/code** not **/phpweb** - is your site.conf file correct?
I created subfolder in the code/ folder and I can see files in this subfolder. For my location: 
```
http://php-docker.local:8080/subfolder/file_in_subfolder.php
```
Source code subfolder/file_in_subfolder.php:
```php
<?php
echo "I'm in subfolder: ".dirname(__FILE__);
```
I see the result:
```html
I'm in subfolder: /code/subfolder.
```
